routes/web.php
<?php

use App\HistoriaAudiometria;
use App\Paciente;

// DB::listen(function($query){
// 	echo "<pre>{$query->time}</pre>";
// });
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//-----------------------------------------Patient-----------------------------------------------------
Route::get('/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);

//Route::get('login',['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);

Route::post('login', 'Auth\LoginController@login');

Route::get('logout', 'Auth\LoginController@logout')->name('login');

Route::get('paciente/registrar', 'PatientController@create')->name('paciente.create');

Route::post('paciente', 'PatientController@store')->name('paciente.store');

Route::get('paciente/buscar', 'PatientController@viewList')->name('paciente.viewList');

Route::post('paciente/buscar', 'PatientController@findByDocumentOrName');

Route::get('paciente/resultados', 'PatientController@findByDocumentOrName')->name('paciente.findByDocumentOrName');

Route::get('paciente/editar/{id}', 'PatientController@edit')->name('paciente.edit');

Route::post('paciente/update/{id}', 'PatientController@update')->name('paciente.update');

Route::post('paciente/findByDocument', 'PatientController@findByDocument')->name('paciente.findByDocument');

Route::get('usuario/buscarHistorias', 'PatientController@viewHistorias')->name('paciente.viewHistorias');

Route::post('paciente/historias', 'PatientController@getAllHistories')->name('paciente.historias');

//-----------------------------------------Usuario-----------------------------------------------------

Route::get('usuario/registrar', 'UserController@create')->name('usuario.create');

Route::post('usuario', 'UserController@store')->name('usuario.store');

Route::get('usuario/buscar', 'UserController@viewList')->name('usuario.viewList');

Route::post('usuario/buscar', 'UserController@findByDocumentOrName')->name('usuario.findByDocumentOrName');

Route::get('usuario/editar/{id}', 'UserController@edit')->name('usuario.edit');

Route::post('usuario/update/{id}', 'UserController@update')->name('usuario.update');

Route::get('usuario/restablecerContrasenia', 'UserController@viewRecoverPassword')->name('usuario.viewRecoverPass');

Route::post('usuario/restablecerContrasenia', 'UserController@recoverPassword')->name('usuario.recoverPassword');

//-----------------------------------------Empresa-----------------------------------------------------

Route::get('empresa/registrar', 'CompanyController@create')->name('empresa.create');

Route::post('empresa','CompanyController@store')->name('empresa.store');

Route::get('empresa/buscar', 'CompanyController@viewList')->name('empresa.viewList');

Route::post('empresa/buscar', 'CompanyController@findByNitOrName')->name('empresa.findByNitOrName');

Route::get('empresa/editar/{id}', 'CompanyController@edit')->name('empresa.edit');

Route::post('empresa/update/{id}', 'CompanyController@update')->name('empresa.update');

Route::post('empresa/autocomplete', 'CompanyController@autocompleteCompany')->name('empresa.autocomplete');

//-----------------------------------------Historia Clinica-----------------------------------------------------

Route::get('historiaClinica/registrar', 'HistoriaClinicaController@create')->name('historiaClinica.create');

Route::post('historiaClinica/registrar','HistoriaClinicaController@store')->name('historiaClinica.store');

Route::post('historiaClinica/buscarCIE10','HistoriaClinicaController@buscarCIE10')->name('historiaClinica.buscarCIE10');

Route::get('historia/hc/{id}', 'HistoriaClinicaController@getHCWeb')->name('historiaClinica.getHC');

Route::post('hc/autocomplete', 'HistoriaClinicaController@autocompleteDiagnostico')->name('cie10.autocomplete');

Route::post('hc/update/{id}', 'HistoriaClinicaController@update')->name('hc.update');

Route::post('hc/cerrar/{id}', 'HistoriaClinicaController@cerrarHistoriaClinica')->name('hc.cerrar');

Route::post('hc/anular', 'HistoriaClinicaController@anularHistoriaClinica')->name('hc.anular');

Route::post('hc/crearNota', 'HistoriaClinicaController@crearNotaEvolucion')->name('hc.crearnota');

Route::get('hc/atenciones', 'HistoriaClinicaController@viewVistaAdministrativa')->name('historiaClinica.viewAtenncionesGenerales');

Route::get('hc/atencionesPage', 'HistoriaClinicaController@atencionesPorCriterio')->name('historiaclinica.atencionesPage');

//-----------------------------------------reportes-----------------------------------------------------

Route::get('historiaClinica/reporteDiagnostico', 'ReportController@view')->name('historia.reporteDiag');

Route::get('historiaClinica/{id}', 'HistoriaClinicaController@show');

Route::get('historiaOptometria/{id}', 'HistoriaOptometriaController@show');

Route::post('historiaClinica/reporteDiagnostico','ReportController@generateReport')->name('historia.generarDiag');

Route::get('reportes/reporteOptometria', 'CertificadoOptometriaController@view')->name('optometria.reporte');

Route::get('reportes/reporteOptometria/{id}','CertificadoOptometriaController@generateCertificate')->name('optometria.generarCertificado');

Route::get('reportes/reporteClinico/{id}','CertificadoHistoriaClinicaController@generateCertificate')->name('historiaclinica.generarCertificado');

Route::get('reportes/reporteClinicounificado/{id}','CertificadoHistoriaClinicaController@generateCertificateUnificado')->name('historiaclinica.generarInforme');

Route::get('reportes/reporteVisiometria', 'CertificadoVisiometriaController@view')->name('visiometria.reporte');

Route::get('reportes/reporteVisiometria/{id}','CertificadoVisiometriaController@generateCertificate')->name('visiometria.generarCertificado');

Route::get('reportes/reporteAudiometria/{id}','CertificadoAudiometriaController@generateCertificate')->name('audiometria.generarCertificado');

//----------------------------------------------------------------------------------------------

Route::post('registro', 'pagesController@registerPatient');

//-----------------------------------------Historia Optometria------------------------------------------

Route::resource('/optometria', 'HistoriaOptometriaController');

Route::get('historiaOptometria/{id}', 'HistoriaOptometriaController@getHOWeb')->name('historiaOptometria.getHO');

Route::post('ho/anular', 'HistoriaOptometriaController@anular')->name('ho.anular');

Route::get('/print/opto/{id}', 'HistoriaOptometriaController@print');

Route::get('/print/opto2/{id}', 'HistoriaOptometriaController@print2');

//-----------------------------------------Historia Visiometria------------------------------------------

Route::get('visiometria/register', 'HistoriaVisiometriaController@create')->name('historiaVisiometria.create');

Route::post('visiometria/register', 'HistoriaVisiometriaController@store')->name('historiaVisiometria.store');

Route::get('historiaVisiometria/{id}', 'HistoriaVisiometriaController@getHVWeb')->name('historiaVisiometria.getHV');

Route::post('hv/anular', 'HistoriaVisiometriaController@anular')->name('hv.anular');

//-----------------------------------------Historia Audiometria------------------------------------------

Route::get('audiometria/register', 'HistoriaAudiometriaController@create')->name('historiaAudiometria.register');

Route::post('audiometria/register', 'HistoriaAudiometriaController@store')->name('historiaAudiometria.store');

Route::get('audiometria/{id}', 'HistoriaAudiometriaController@getHAWeb')->name('historiaAudiometria.getHA');
/*Route::get('audiometria/{id}', function ($id){
    $historia = HistoriaAudiometria::with([
        'antecedentes',
        'otoscopia',
        'recomendacion',
        'audiograma', 'empresa'
    ])->find(decrypt($id));
    return $historia;
});*/

Route::post('ha/anular', 'HistoriaAudiometriaController@anular')->name('ha.anular');

//-----------------------------------------EXPORT--------------------------------------------------------

Route::get('export/bd', 'HistoriaClinicaController@viewExportDataBase')->name('historiaClinica.viewExport');

Route::get('export/historiaclinica', 'HistoriaClinicaController@export')->name('historiaClinica.export');

resources/views/home.blade.php
@extends('layouts')

@section('contenido')
    <h1>Home</h1>
@stop

resources/views/layouts.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="\css\app.css">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="/js/app.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{{asset('/css/bootstrap-datepicker3.css')}}">
    <link rel="stylesheet" href="{{asset('/css/bootstrap-datepicker.standalone.css')}}">
    <script src="{{asset('/js/bootstrap-datepicker.js')}}"></script>
{{--    <meta http-equiv="Expires" content="0" />--}}
{{--    <meta http-equiv="Pragma" content="no-cache" />--}}

{{--    <script type="text/javascript">--}}
{{--        if(history.forward(1)){--}}
{{--            location.replace( history.forward(1) );--}}
{{--        }--}}
{{--    </script>--}}
    @yield('js')
    <!-- Languaje -->
    <script src="{{asset('/js/bootstrap-datepicker.es.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <link rel="icon" type="image/ico" href="/img/favicon-analizar[1].png" />
    @if(request()->is('/'))
        <title>Inicio de sesión</title>
    @endif
    @yield('title')
</head>
<body>
    <header>
        <div class="container-local">
            @if(auth()->check())
                <div class="row margin-header">
                    <div class="col-md-6">
                        <img src="/img/analizar-logo.png" class="size-img">
                    </div>
                    <div class="col-md-3 offset-md-3 logout">
                        <a href="/logout">Cerrar sesión de {{ auth()->user()->name }}</a>
                    </div>
                </div>
            @endif
            @if(auth()->check())
                <nav class="navbar navbar-expand-lg navbar-light menu justify-content-center">
                    <div class="mx-auto d-sm-flex d-block flex-sm-nowrap">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        
                        <div class="collapse navbar-collapse style-dropdown" id="navbarSupportedContent">
                            <ul class="navbar-nav mr-auto">
                                @if(auth()->user()->hasRoles(['admin']))
                                    <li class="nav-item dropdown {{ setActive('usuario/registrar') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            USUARIO
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('usuario.create') }}">REGISTRAR</a>
                                            <a class="dropdown-item" href="{{ route('usuario.viewList') }}">BUSCAR</a>
                                            <a class="dropdown-item" href="{{ route('usuario.viewRecoverPass') }}">RESTABLECER CONTRASEÑA</a>
                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['medico','admin','fonoaudiologa','optometra','recepcionista']))
                                    <li class="nav-item dropdown {{ setActive('paciente/registrar') }} {{ setActive('paciente/buscar') }} {{ setActive('paciente/editar/*') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            PACIENTE
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('paciente.create') }}">REGISTRAR</a>
                                            <a class="dropdown-item" href="{{ route('paciente.viewList') }}">BUSCAR</a>
                                            <a class="dropdown-item" href="{{ route('paciente.viewHistorias') }}">CONSULTAR HISTORIAS</a>
                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['medico','admin']))
                                    <li class="nav-item dropdown {{ setActive('') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            HISTORIA CLíNICA
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('historiaClinica.create') }}">REGISTRAR</a>
                                            @if(auth()->user()->hasRoles(['admin']))
                                                <a class="dropdown-item" href="{{ route('historiaClinica.viewAtenncionesGenerales') }}">VISIÓN GENERAL ATENCIONES</a>
                                            @endif

                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['medico','admin','optometra',]))
                                    <li class="nav-item dropdown {{ setActive('') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            HISTORIA OPTOMETRÍA
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('optometria.index') }}">REGISTRAR</a>
                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['medico','admin','optometra',]))
                                    <li class="nav-item dropdown {{ setActive('') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            HISTORIA VISIOMETRÍA
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('historiaVisiometria.create') }}">REGISTRAR</a>
                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['medico','admin','fonoaudiologa']))
                                    <li class="nav-item dropdown {{ setActive('') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            HISTORIA AUDIOMETRÍA
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('historiaAudiometria.register') }}">REGISTRAR</a>
                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['admin']))
                                    <li class="nav-item dropdown {{ setActive('') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            EMPRESA
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('empresa.create') }}">REGISTRAR</a>
                                            <a class="dropdown-item" href="{{ route('empresa.viewList') }}">BUSCAR</a>
                                        </div>
                                    </li>
                                @endif
                                @if(auth()->user()->hasRoles(['medico','admin']))
                                    <li class="nav-item dropdown {{ setActive('') }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            REPORTES
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('historia.reporteDiag') }}">REPORTE DIAGNOSTICO</a>
                                            <a class="dropdown-item" href="{{ route('historiaClinica.viewExport') }}">EXPORTACIÓN BASE DE DATOS</a>
                                        </div>
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </nav>
            @endif
        </div>
    </header>
    @yield('contenido')
    @if(auth()->check())
        <br>

        <footer>
            <div class="container-footer">
                <div class="row">
                    <div class="col-md-12" style="padding-left: 0">
                        <h6 class="">Analizar laboratorio clínico automatizado © {{ date('Y') }}</h6>
                    </div>
                </div>
            </div>
        </footer>
    @endif
</body>
</html>